### ISSUE TITLE
broken link?

### ISSUE THREAD

**Issue by shadiakiki1986** [theonion/django-bulbs#338]
I just tried to follow the link in the deprecation note, but it's broken. Also just tried to search for the repo `theonion/omni` and couldn't try to figure it out. Would you mind providing an updated link?

**Comment by mparent61** [comment]
Hi @shadiakiki1986 - The `theonion/omni` repo is private. We had to make the difficult decision to move `django-bulbs` to private development, given resource limitations.

**Comment by shadiakiki1986** [comment]
Ok thanks!

**Comment by shadiakiki1986** [comment]
I'm just drafting an answer to [this SO question](https://stackoverflow.com/questions/23759184/graph-db-with-django) and linking to this issue if you don't mind
