### ISSUE TITLE
clean up dependencies

### ISSUE THREAD

**Issue by vforgione** [theonion/django-bulbs#35]
there's a lot of shit in the `requirements.txt` and `requirements-dev.txt` files that needs to be either updated, frozen or removed (I'm looking at you, South).

**Comment by mparent61** [comment]
HAHAHA I thought we got rid of you???

**Comment by MichaelButkovic** [comment]
LGTM

**Comment by mparent61** [comment]
Can we send you a few tickets?

**Comment by vforgione** [comment]
Ha. I was cleaning out my backlog. Miss you guys 😿

**Comment by vforgione** [comment]
Plus there isn't even a requirements file anymore... 👍
